version: '3'

services:
  app:
    container_name: app
    restart: always
    build: ./app
    environment:
      - aws_access_key_id = ${aws_access_key_id}
      - aws_secret_access_key = ${aws_secret_access_key}
    ports:
      - "8501:8501"
    command: streamlit run app.py

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
