version: '3'

services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "8501:8501"
    environment:
      - AWS_PROFILE=default
    volumes:
      - ~/.aws/:/root/.aws:ro
    command: streamlit run app.py

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
